### ISSUE TITLE
Error unbinding ssl profile from cs vserver

### ISSUE THREAD

**Issue by vintury** [citrix/terraform-provider-citrixadc#93]
Hello.
After enabling default ssl profile terraform can't destroy cs vs with SSL type, if it binded to default ssl profile.

 Error: [ERROR] netscaler-provider: Error unbinding ssl profile from csvserver tf-10.0.0.2_443_SSL
   on .terraform/modules/create_http_balancer/main.tf line 20, in resource "citrixadc_csvserver" "resource_vpx_csvs":
   20: resource "citrixadc_csvserver" "resource_vpx_csvs" {

Reproduce:
1) adc cli: set ssl parameter -defaultProfile ENABLED
2) apply resource "citrixadc_csvserver" without specific sslprofile.
For example:
'
resource "citrixadc_csvserver" "resource_vpx_csvs" {
  name        = "tf-10.0.0.2_443_SSL"
  ipv46       = "10.0.0.2"
  port        = "443"
  servicetype = "SSL"
  sslcertkey  = citrixadc_sslcertkey.generic-cert.certkey
   #sslprofile  = "ns_default_ssl_profile_frontend"
'
3) destroy resource "citrixadc_csvserver"

**Comment by vadharm** [comment]
Will triage and get a fix.

**Comment by giorgos-nikolopoulos** [comment]
I have verified this error.

We will need to refactor the csvserver resource along with a new resource for explicitly defined sslveserver and sslcertkey bindings.
Related to #81.

Will pick this up when time permits.

**Comment by giorgos-nikolopoulos** [comment]
It seems this is the expected behavior from the csvserver resource.

What the provider tries to do is correct in its view of the remote and local state.

Remote state says there is a sslprofile bound to the server.
Local state says there should be no profile bound.
So in the effort to apply the local state to the remote state it tries to remove the default sslprofile which fails because the default SSL profile option is set on the target ADC.

If the user sets `sslprofile = "ns_default_ssl_profile_frontend"` then creation and destruction works as expected.

We could write a special case for the default profile not to be removed but this will be come a liability should the default profile name change.

I think it's preferable to leave the resource as is and the user can handle this case by simply adding the default profile explicitly in the resource block.
